# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Starter.destroy_all
Flavor.destroy_all
Finale.destroy_all

Starter.create(name: "Mountain")
Starter.create(name: "Ocean")
Starter.create(name: "Forrest")
Starter.create(name: "Space")
Starter.create(name: "Colorado")
Starter.create(name: "Cali")
Starter.create(name: "Arctic")
Starter.create(name: "Scooby's")
Starter.create(name: "Cabin")
Starter.create(name: "Wild")
Starter.create(name: "Grateful")
Starter.create(name: "Golden")
Starter.create(name: "Bayou")
Starter.create(name: "Pirate")
Starter.create(name: "Shaggy")
Starter.create(name: "Super")
Starter.create(name: "Fatty")
Starter.create(name: "Alaskan")
Starter.create(name: "Norwegian")
Starter.create(name: "King")
Starter.create(name: "Aspen")
Starter.create(name: "Coders")
Starter.create(name: "Pine")
Starter.create(name: "Ghost")
Starter.create(name: "Alien")
Starter.create(name: "Whiches")
Starter.create(name: "Sour")
Starter.create(name: "Granddaddy")
Starter.create(name: "Bootylicious")
Starter.create(name: "Penguin")
Starter.create(name: "Snoop's")

Flavor.create(name: "berry")
Flavor.create(name: "cherry")
Flavor.create(name: "mandarin")
Flavor.create(name: "grape")
Flavor.create(name: "cookie")
Flavor.create(name: "blackberry")
Flavor.create(name: "gangsta")
Flavor.create(name: "watermelon")
Flavor.create(name: "snow")
Flavor.create(name: "apple")
Flavor.create(name: "lemon")
Flavor.create(name: "harmony")
Flavor.create(name: "tropic")
Flavor.create(name: "pineapple")
Flavor.create(name: "melon")
Flavor.create(name: "homie")
Flavor.create(name: "honey")
Flavor.create(name: "sweet")
Flavor.create(name: "banana")
Flavor.create(name: "purple")
Flavor.create(name: "thunder")
Flavor.create(name: "candy")
Flavor.create(name: "moonlight")
Flavor.create(name: "sunshine")
Flavor.create(name: "fuzzy")

Finale.create(name: "funk!")
Finale.create(name: "skunk!")
Finale.create(name: "stank!")
Finale.create(name: "kush!")
Finale.create(name: "OG!")
Finale.create(name: "fuck!")
Finale.create(name: "cheese!")
Finale.create(name: "stomper!")
Finale.create(name: "shizz!")
Finale.create(name: "greens!")
Finale.create(name: "blaster!")
Finale.create(name: "fluff")
Finale.create(name: "crasher!")
Finale.create(name: "smoke!")
Finale.create(name: "chronic!")
Finale.create(name: "knock-out!")
Finale.create(name: "chunk!")
Finale.create(name: "crunk!")
Finale.create(name: "cough!")
Finale.create(name: "crack!")
Finale.create(name: "flow!")